sequenceDiagram
    actor User
    participant GatewayServise
    box LightYellow Stream
    participant Question
    end
    box LightYellow Stream
    participant Answer
    end
    participant DistributerService
    box LightYellow Stream
    participant TimeQuestion
    end
    participant TimeService
    box LightYellow Stream
    participant DateQuestion
    end
    participant DateService
    User->>+GatewayServise : asks 'Time/Date'
    GatewayServise--)Question : Supply
    Question--)DistributerService : to Consume
    DistributerService-->>DistributerService : decides to whom should give the question
    par Time question
        DistributerService--)TimeQuestion : Supply
        TimeQuestion--)TimeService : to Consume
        TimeService-->>TimeService : calculates Time
        TimeService--)Answer : Supply
    and Date questoin
        DistributerService--)DateQuestion : Supply
        DateQuestion--)DateService : to Consume
        DateService-->>DateService : calculates Date
        DateService--)Answer : Supply    
    end
    Answer--)GatewayServise : to Consume
    GatewayServise->>-User : the Answer
