spring:
  main:
    web-application-type: none

spring.cloud.function:
  definition: dateProcessor

spring.cloud.stream:
  defaultBinder: rabbit
  bindings:
    dateProcessor-in-0:
      destination: dateQuestions
    dateProcessor-out-0:
      destination: answers

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    com.gilmard: DEBUG

---
spring.config.activate.on-profile: docker
spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka

---
spring.config.activate.on-profile: kafka
management.health.rabbit.enabled: false
spring.cloud.stream.defaultBinder: kafka
spring.kafka.bootstrap-servers: kafka:9092
#spring.cloud.stream.kafka.binder.replication-factor: 1
