server:
  port: 7070
  error.include-message: always

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: com.gilmard.microservices.ask.me
  pathsToMatch: /**

api:
  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfService: MY TERMS OF SERVICE
    license: MY LICENSE
    licenseUrl: MY LICENSE URL
    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: NAME OF CONTACT
      url: URL TO CONTACT
      email: contact@mail.com

spring.cloud.function:
  definition: questionProcessor;answerConsumer
spring.cloud.stream:
  defaultBinder: rabbit
  bindings:
    questionProcessor-in-0:
      destination: questions
    questionProcessor-out-0:
      destination: answers
    answerConsumer-in-0:
      destination: answers

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    com.gilmard: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080
spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka

